version: "3"
services:
  frontend:
    image: adritek/dcslgs-frontend:latest
    stdin_open: true
    ports: 
      - "3000:8080"
    networks:
      - mern-app
  backend:
    image: adritek/dcslgs-backend:latest
    ports:
      - "5000:8080"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge